#ifndef JS_BOARD_EDIT_H
#define JS_BOARD_EDIT_H

// Auto-generated from board_edit.js
// DO NOT EDIT THIS FILE DIRECTLY - Edit js_source/board_edit.js instead
// Run 'npm run build' or 'yarn build' to regenerate

#define JS_BOARD_EDIT \
"function initBoardEdit(){fetch(\"/board\").then(e=>e.json()).then(e=>{e.valid?renderEditBoard(e.board):renderEditBoard(Array(8).fill(null).map(()=>Array(8).fill(\"\")))}).catch(e=>{console.error(\"Error fetching board state:\",e),renderEditBoard(Array(8).fill(null).map(()=>Array(8).fill(\"\")))})}function renderEditBoard(e){const l=document.getElementById(\"chess-board\");l.innerHTML=\"\";const a=[{value:\"\",label:\"\"},{value:\"R\",label:\"♖ R\"},{value:\"N\",label:\"♘ N\"},{value:\"B\",label:\"♗ B\"},{value:\"Q\",label:\"♕ Q\"},{value:\"K\",label:\"♔ K\"},{value:\"P\",label:\"♙ P\"},{value:\"r\",label:\"♜ r\"},{value:\"n\",label:\"♞ n\"},{value:\"b\",label:\"♝ b\"},{value:\"q\",label:\"♛ q\"},{value:\"k\",label:\"♚ k\"},{value:\"p\",label:\"♟ p\"}];for(let t=0;t<8;t++)for(let n=0;n<8;n++){const r=(t+n)%2==0,d=document.createElement(\"div\");d.className=\"square \"+(r?\"light\":\"dark\");const o=document.createElement(\"select\");o.name=\"r\"+t+\"c\"+n,o.id=\"r\"+t+\"c\"+n;const i=e[t][n]||\"\";a.forEach(e=>{const l=document.createElement(\"option\");l.value=e.value,l.textContent=e.label,(e.value===i||\" \"===i&&\"\"===e.value)&&(l.selected=!0),o.appendChild(l)}),d.appendChild(o),l.appendChild(d)}}\"loading\"===document.readyState?document.addEventListener(\"DOMContentLoaded\",initBoardEdit):initBoardEdit();"

#endif // JS_BOARD_EDIT_H
