#ifndef JS_BOARD_UPDATE_H
#define JS_BOARD_UPDATE_H

// Auto-generated from board_update.js
// DO NOT EDIT THIS FILE DIRECTLY - Edit js_source/board_update.js instead
// Run 'npm run build' or 'yarn build' to regenerate

#define JS_BOARD_UPDATE \
"function updateBoard(){fetch(\"/board\").then(e=>e.json()).then(e=>{if(e.valid){const t=document.querySelectorAll(\".square\");let n=0;for(let o=0;o<8;o++)for(let a=0;a<8;a++){const c=e.board[o][a],l=t[n];if(c&&\"\"!==c){const e=c===c.toUpperCase();l.innerHTML='<span class=\"piece '+(e?\"white\":\"black\")+'\">'+getPieceSymbol(c)+\"</span>\"}else l.innerHTML=\"\";n++}}})}"

#endif // JS_BOARD_UPDATE_H
