#ifndef JS_PIECE_SYMBOLS_H
#define JS_PIECE_SYMBOLS_H

// Auto-generated from piece_symbols.js
// DO NOT EDIT THIS FILE DIRECTLY - Edit js_source/piece_symbols.js instead
// Run 'npm run build' or 'yarn build' to regenerate

#define JS_PIECE_SYMBOLS \
"function getPieceSymbol(e){if(!e)return\"\";return{R:\"♖\",N:\"♘\",B:\"♗\",Q:\"♕\",K:\"♔\",P:\"♙\",r:\"♜\",n:\"♞\",b:\"♝\",q:\"♛\",k:\"♚\",p:\"♟\"}[e]||e}"

#endif // JS_PIECE_SYMBOLS_H
