#ifndef HTML_BOARD_EDIT_CONTENT_H
#define HTML_BOARD_EDIT_CONTENT_H

// Auto-generated from board_edit.html
// DO NOT EDIT THIS FILE DIRECTLY - Edit html_source/board_edit.html instead
// Run 'npm run build' or 'yarn build' to regenerate

#define HTML_BOARD_EDIT_CONTENT \
"<div class=\"container\"><h2>EDIT CHESS BOARD</h2><div class=\"status\">Click on any square to change the piece. Empty = no piece.</div><div id=\"board-container\" class=\"board-container\"><form id=\"boardForm\" method=\"POST\" action=\"/board-edit\"><div class=\"board\" id=\"chess-board\"></div><div class=\"controls\"><button type=\"submit\" class=\"button\">Save Board State</button> <button type=\"button\" class=\"button secondary\" onclick=\"location.reload()\">Reset</button></div></form></div><div class=\"info\"><p>Changes will be applied to the current game state.</p></div><a href=\"/board-view\" class=\"back-button\">Back to Board View</a> <a href=\"/\" class=\"back-button\">Back to Configuration</a></div>"

#endif // HTML_BOARD_EDIT_CONTENT_H
