#ifndef HTML_BOARD_EDIT_STYLES_H
#define HTML_BOARD_EDIT_STYLES_H

// Auto-generated from board_edit_styles.css
// DO NOT EDIT THIS FILE DIRECTLY - Edit html_source/board_edit_styles.css instead
// Run 'npm run build' or 'yarn build' to regenerate

#define HTML_BOARD_EDIT_STYLES \
"body{font-family:Arial,sans-serif;background-color:#5c5d5e;margin:0;padding:20px}.container{background-color:#353434;border-radius:8px;box-shadow:0 4px 8px rgba(0,0,0,.1);padding:30px;max-width:800px;margin:0 auto}h2{text-align:center;color:#ec8703;font-size:24px;margin-bottom:20px}.board-container{display:inline-block;margin:20px auto}.board{display:grid;grid-template-columns:repeat(8,1fr);gap:0;border:3px solid #ec8703;width:480px;height:480px}.square{width:60px;height:60px;display:flex;align-items:center;justify-content:center;position:relative}.square.light{background-color:#f0d9b5}.square.dark{background-color:#b58863}.square:hover{background-color:#ec8703!important;opacity:.8}.square select{width:100%;height:100%;border:0;background:0 0;font-size:32px;text-align:center;cursor:pointer;appearance:none;-webkit-appearance:none;-moz-appearance:none}.square select:focus{outline:2px solid #ec8703}.controls{text-align:center;margin-top:20px}.button{background-color:#ec8703;color:#fff;border:0;padding:15px 30px;font-size:16px;border-radius:5px;cursor:pointer;margin:10px}.button:hover{background-color:#ebca13}.button.secondary{background-color:#666}.button.secondary:hover{background-color:#777}.button.paused{background-color:#f44336}.button.paused:hover{background-color:#d32f2f}.info{text-align:center;color:#ec8703;margin-top:20px;font-size:14px}.back-button{background-color:#666;color:#fff;border:0;padding:15px;font-size:16px;width:100%;border-radius:5px;cursor:pointer;text-decoration:none;display:block;text-align:center;margin-top:20px}.back-button:hover{background-color:#777}.status{text-align:center;color:#ec8703;margin-bottom:20px;padding:10px;background-color:#444;border-radius:5px}"

#endif // HTML_BOARD_EDIT_STYLES_H
