#ifndef HTML_COMMON_STYLES_H
#define HTML_COMMON_STYLES_H

// Auto-generated from common_styles.css
// DO NOT EDIT THIS FILE DIRECTLY - Edit html_source/common_styles.css instead
// Run 'npm run build' or 'yarn build' to regenerate

#define HTML_COMMON_STYLES \
"body{font-family:Arial,sans-serif;background-color:#5c5d5e;margin:0;padding:0;display:flex;justify-content:center;align-items:center;min-height:100vh}.container{background-color:#353434;border-radius:8px;box-shadow:0 4px 8px rgba(0,0,0,.1);padding:30px;width:100%;max-width:500px}h2{text-align:center;color:#ec8703;font-size:24px;margin-bottom:20px}label{font-size:16px;color:#ec8703;margin-bottom:8px;display:block}input[type=text],input[type=password],select{width:100%;padding:10px;margin:10px 0;border:1px solid #ccc;border-radius:5px;box-sizing:border-box;font-size:16px}input[type=submit],.button{background-color:#ec8703;color:#fff;border:0;padding:15px;font-size:16px;width:100%;border-radius:5px;cursor:pointer;transition:background-color .3s ease;text-decoration:none;display:block;text-align:center;margin:10px 0}input[type=submit]:hover,.button:hover{background-color:#ebca13}.form-group{margin-bottom:15px}.note{font-size:14px;color:#ec8703;text-align:center;margin-top:20px}"

#endif // HTML_COMMON_STYLES_H
