#ifndef HTML_GAME_SELECTION_CONTENT_H
#define HTML_GAME_SELECTION_CONTENT_H

// Auto-generated from game_selection.html
// DO NOT EDIT THIS FILE DIRECTLY - Edit html_source/game_selection.html instead
// Run 'npm run build' or 'yarn build' to regenerate

#define HTML_GAME_SELECTION_CONTENT \
"<div class=\"game-selection-container\"><div class=\"player-selection\"><h3>Select White Player</h3><div class=\"player-options\"><div class=\"player-option\" onclick='selectPlayer(\"white\",0)'><span class=\"player-icon\">👤</span> <span class=\"player-label\">Human</span></div><div class=\"player-option\" onclick='selectPlayer(\"white\",1)'><span class=\"player-icon\">🤖</span> <span class=\"player-label\">Easy AI</span></div><div class=\"player-option\" onclick='selectPlayer(\"white\",2)'><span class=\"player-icon\">🤖</span> <span class=\"player-label\">Medium AI</span></div><div class=\"player-option\" onclick='selectPlayer(\"white\",3)'><span class=\"player-icon\">🤖</span> <span class=\"player-label\">Hard AI</span></div></div></div><div class=\"player-selection\"><h3>Select Black Player</h3><div class=\"player-options\"><div class=\"player-option\" onclick='selectPlayer(\"black\",0)'><span class=\"player-icon\">👤</span> <span class=\"player-label\">Human</span></div><div class=\"player-option\" onclick='selectPlayer(\"black\",1)'><span class=\"player-icon\">🤖</span> <span class=\"player-label\">Easy AI</span></div><div class=\"player-option\" onclick='selectPlayer(\"black\",2)'><span class=\"player-icon\">🤖</span> <span class=\"player-label\">Medium AI</span></div><div class=\"player-option\" onclick='selectPlayer(\"black\",3)'><span class=\"player-icon\">🤖</span> <span class=\"player-label\">Hard AI</span></div></div></div><div class=\"start-game-container\"><button id=\"start-game-btn\" class=\"start-game-button\" onclick=\"startGame()\" disabled=\"disabled\">Start Game</button></div><div class=\"sensor-test-container\"><button class=\"sensor-test-button\" onclick=\"selectSensorTest()\">Sensor Test</button></div></div>"

#endif // HTML_GAME_SELECTION_CONTENT_H
