#ifndef HTML_GAME_SELECTION_STYLES_H
#define HTML_GAME_SELECTION_STYLES_H

// Auto-generated from game_selection_styles.css
// DO NOT EDIT THIS FILE DIRECTLY - Edit html_source/game_selection_styles.css instead
// Run 'npm run build' or 'yarn build' to regenerate

#define HTML_GAME_SELECTION_STYLES \
"body{font-family:Arial,sans-serif;background-color:#5c5d5e;margin:0;padding:0;display:flex;justify-content:center;align-items:center;min-height:100vh}.container{background-color:#353434;border-radius:8px;box-shadow:0 4px 8px rgba(0,0,0,.1);padding:30px;width:100%;max-width:600px}h2{text-align:center;color:#ec8703;font-size:24px;margin-bottom:30px}.game-grid{display:grid;grid-template-columns:1fr 1fr;gap:20px;margin-bottom:30px}.game-mode{background-color:#444;border:2px solid #ec8703;border-radius:8px;padding:20px;text-align:center;cursor:pointer;transition:all .3s ease;color:#fff}.game-mode:hover{background-color:#ec8703;transform:translateY(-2px)}.game-mode.available{border-color:#4caf50}.game-mode.coming-soon{border-color:#888;opacity:.6}.game-mode.mode-1{border-color:#ff9800;background:linear-gradient(135deg,#444 0,#ff9800 100%)}.game-mode.mode-2{border-color:#fff;background:linear-gradient(135deg,#444 0,#fff 100%)}.game-mode.mode-3{border-color:#2196f3;background:linear-gradient(135deg,#444 0,#2196f3 100%)}.game-mode.mode-4{border-color:#f44336;background:linear-gradient(135deg,#444 0,#f44336 100%)}.game-mode h3{margin:0 0 10px 0;font-size:18px}.game-mode p{margin:0;font-size:14px;opacity:.8}.status{font-size:12px;padding:5px 10px;border-radius:15px;margin-top:10px;display:inline-block}.available .status{background-color:#4caf50;color:#fff}.coming-soon .status{background-color:#888;color:#fff}.back-button{background-color:#666;color:#fff;border:0;padding:15px;font-size:16px;width:100%;border-radius:5px;cursor:pointer;text-decoration:none;display:block;text-align:center;margin-top:20px}.back-button:hover{background-color:#777}"

#endif // HTML_GAME_SELECTION_STYLES_H
