#ifndef HTML_GAME_SELECTION_SCRIPT_H
#define HTML_GAME_SELECTION_SCRIPT_H

// Auto-generated from game_selection.js
// DO NOT EDIT THIS FILE DIRECTLY - Edit html_source/game_selection.js instead
// Run 'npm run build' or 'yarn build' to regenerate

#define HTML_GAME_SELECTION_SCRIPT \
"let selectedWhite=null,selectedBlack=null;function selectPlayer(e,t){document.querySelectorAll(`.player-selection:has(.player-option[onclick*=\"${e}\"]) .player-option`).forEach(e=>e.classList.remove(\"selected\")),event.target.closest(\".player-option\").classList.add(\"selected\"),\"white\"===e?selectedWhite=t:selectedBlack=t;const l=document.getElementById(\"start-game-btn\");null!==selectedWhite&&null!==selectedBlack&&(l.disabled=!1)}function startGame(){if(null===selectedWhite||null===selectedBlack)return void alert(\"Please select both players\");const e={white:selectedWhite,black:selectedBlack};fetch(\"/gameselect\",{method:\"POST\",headers:{\"Content-Type\":\"application/json\"},body:JSON.stringify(e)}).then(e=>e.json()).then(e=>{alert(\"Game started! White: \"+getPlayerName(selectedWhite)+\", Black: \"+getPlayerName(selectedBlack))}).catch(e=>{console.error(\"Error:\",e);fetch(\"/gameselect\",{method:\"POST\",headers:{\"Content-Type\":\"application/x-www-form-urlencoded\"},body:\"white=\"+selectedWhite+\"&black=\"+selectedBlack}).then(e=>e.text()).then(e=>{alert(\"Game started! White: \"+getPlayerName(selectedWhite)+\", Black: \"+getPlayerName(selectedBlack))}).catch(e=>{console.error(\"Error:\",e),alert(\"Failed to start game\")})})}function selectSensorTest(){fetch(\"/gameselect\",{method:\"POST\",headers:{\"Content-Type\":\"application/x-www-form-urlencoded\"},body:\"gamemode=4\"}).then(e=>e.text()).then(e=>{alert(\"Sensor Test mode selected!\")}).catch(e=>{console.error(\"Error:\",e),alert(\"Failed to select sensor test\")})}function getPlayerName(e){switch(e){case 0:return\"Human\";case 1:return\"Easy AI\";case 2:return\"Medium AI\";case 3:return\"Hard AI\";default:return\"Unknown\"}}"

#endif // HTML_GAME_SELECTION_SCRIPT_H
