#ifndef HTML_GAME_SELECTION_CONTENT_H
#define HTML_GAME_SELECTION_CONTENT_H

// Auto-generated from game_selection.html
// DO NOT EDIT THIS FILE DIRECTLY - Edit html_source/game_selection.html instead
// Run 'npm run build' or 'yarn build' to regenerate

#define HTML_GAME_SELECTION_CONTENT \
"<div class=\"game-grid\"><div class=\"game-mode available mode-1\" onclick=\"selectGame(1)\"><h3>Chess Moves</h3><p>Full chess game with move validation and animations</p><span class=\"status\">Available</span></div><div class=\"game-mode available mode-2\" onclick=\"selectGame(2)\"><h3>Chess Bot</h3><p>Player White vs AI Black (Medium)</p><span class=\"status\">Available</span></div><div class=\"game-mode available mode-3\" onclick=\"selectGame(3)\"><h3>Black AI Stockfish</h3><p>Player Black vs AI White</p><span class=\"status\">Available</span></div><div class=\"game-mode available mode-4\" onclick=\"selectGame(4)\"><h3>Sensor Test</h3><p>Test and calibrate board sensors</p><span class=\"status\">Available</span></div><div class=\"game-mode available mode-5\" onclick=\"selectGame(5)\"><h3>Bot vs Bot</h3><p>AI vs AI - Watch two computers play</p><span class=\"status\">Available</span></div></div>"

#endif // HTML_GAME_SELECTION_CONTENT_H
